[package]
name = "mm_arl"
version = "1.0.0"

[dependencies]
lfa = "0.14"
rsrl = "0.7"

rand = "0.7"
rand_distr = "0.2"

csv = "1.0"
slog = "2.3"
clap = "2.33"
rayon = "1.0"

serde = "1.0"
serde_derive = "1.0"
